"""
Django settings for testapi project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d@x6q3exfxq)nyl77vnflk1la5xm$w6-dz@(b8#f1drx%rmsgt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'call_api.apps.CallApiConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'testapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'testapi.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CERTIFICATE = """Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 390571 (0x5f5ab)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=RU, ST=Ufa, L=Ufa, O=slb, CN=slb/emailAddress=support@slb.medv.ru
        Validity
            Not Before: Sep 27 06:40:52 2021 GMT
            Not After : Sep 27 06:40:52 2022 GMT
        Subject: C=RU, ST=Moscow, L=Moscow, O=Test, CN=test@test.test
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:de:bd:32:28:c9:af:7c:42:a6:76:9b:3c:4c:ea:
                    64:c5:70:6e:e9:c2:73:13:d2:7a:06:10:6e:57:25:
                    d5:5c:08:41:c9:2c:94:c4:f0:06:63:e6:d5:b4:6f:
                    2e:91:fc:3c:93:9c:7f:9a:a1:b7:12:0c:76:09:7a:
                    a5:2b:f9:81:eb:44:f1:a3:b5:3f:ff:a7:b9:87:f7:
                    79:3c:1a:79:d2:70:d7:0c:1f:63:50:eb:a4:a8:d6:
                    c8:74:e7:27:1f:72:21:63:54:f2:2e:39:cb:aa:48:
                    29:fa:a2:72:94:36:2e:b6:48:24:00:b6:b3:02:2a:
                    9f:62:57:f6:a3:2c:f7:45:a1:69:af:6e:c5:4e:74:
                    37:10:ce:11:b0:67:0c:33:7c:36:f6:25:ee:cc:89:
                    b8:0d:87:81:70:51:eb:f0:79:ca:9b:98:11:bf:75:
                    88:e7:6f:77:40:19:3d:07:97:0a:f8:95:09:6e:c0:
                    fb:d4:b6:ee:e4:2f:f3:c5:b6:b4:03:d9:30:e8:3f:
                    4a:03:24:bd:ef:b3:1f:bb:11:97:4d:b9:a5:bd:77:
                    1d:54:eb:63:2a:9d:fc:c3:33:dd:b6:51:e8:d7:a2:
                    db:1d:16:96:75:cb:91:55:39:e7:db:d2:77:6c:e3:
                    85:01:a0:b9:ef:d2:4d:70:ba:a7:7e:ee:ad:fa:c8:
                    21:99
                Exponent: 65537 (0x10001)
    Signature Algorithm: sha256WithRSAEncryption
         14:2e:87:da:03:ee:6b:18:16:6c:f0:fc:3d:ad:b3:69:5f:e6:
         2b:20:a2:38:72:1a:e2:cf:94:04:18:73:99:0b:98:4a:1d:49:
         f7:3f:44:a4:96:a1:8d:a0:9e:ee:1c:59:6e:d2:39:3e:28:05:
         94:68:59:e0:3d:49:f5:0c:96:7e:40:64:0c:19:6f:43:05:41:
         3d:86:2b:5f:f3:6e:b5:de:a5:8a:5a:bd:65:4e:ed:de:67:db:
         70:50:95:fb:2f:12:33:ab:42:63:b3:4f:a6:e3:6d:9a:e2:94:
         e8:a0:b5:7b:26:97:85:2b:d9:82:27:08:72:90:1f:c3:f6:4b:
         ce:a8:c6:e2:e1:36:31:0b:69:40:6e:19:20:c9:7a:36:ef:9e:
         d0:16:0c:51:6a:35:78:44:bb:80:70:2e:48:f9:fc:e6:f0:89:
         72:d9:b4:65:6c:c2:64:61:f3:22:55:59:2a:ab:4a:01:6e:f4:
         b5:83:bb:42:44:5a:6d:11:3f:91:ad:e3:0f:ed:35:ba:71:a1:
         5a:f5:de:83:7c:47:88:e6:4d:8f:9c:ea:b5:36:1e:d6:8f:d2:
         90:d0:99:27:07:db:4a:05:65:1d:1b:c0:06:4e:19:e8:1f:42:
         0b:65:15:b6:f6:f8:3b:28:04:73:40:09:4e:24:df:f5:79:ec:
         37:7e:ec:f2
-----BEGIN CERTIFICATE-----
MIIDNjCCAh4CAwX1qzANBgkqhkiG9w0BAQsFADBpMQswCQYDVQQGEwJSVTEMMAoG
A1UECAwDVWZhMQwwCgYDVQQHDANVZmExDDAKBgNVBAoMA3NsYjEMMAoGA1UEAwwD
c2xiMSIwIAYJKoZIhvcNAQkBFhNzdXBwb3J0QHNsYi5tZWR2LnJ1MB4XDTIxMDky
NzA2NDA1MloXDTIyMDkyNzA2NDA1MlowVzELMAkGA1UEBhMCUlUxDzANBgNVBAgM
Bk1vc2NvdzEPMA0GA1UEBwwGTW9zY293MQ0wCwYDVQQKDARUZXN0MRcwFQYDVQQD
DA50ZXN0QHRlc3QudGVzdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
AN69MijJr3xCpnabPEzqZMVwbunCcxPSegYQblcl1VwIQckslMTwBmPm1bRvLpH8
PJOcf5qhtxIMdgl6pSv5getE8aO1P/+nuYf3eTwaedJw1wwfY1DrpKjWyHTnJx9y
IWNU8i45y6pIKfqicpQ2LrZIJAC2swIqn2JX9qMs90Whaa9uxU50NxDOEbBnDDN8
NvYl7syJuA2HgXBR6/B5ypuYEb91iOdvd0AZPQeXCviVCW7A+9S27uQv88W2tAPZ
MOg/SgMkve+zH7sRl025pb13HVTrYyqd/MMz3bZR6Nei2x0WlnXLkVU559vSd2zj
hQGgue/STXC6p37urfrIIZkCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAFC6H2gPu
axgWbPD8Pa2zaV/mKyCiOHIa4s+UBBhzmQuYSh1J9z9EpJahjaCe7hxZbtI5PigF
lGhZ4D1J9QyWfkBkDBlvQwVBPYYrX/Nutd6lilq9ZU7t3mfbcFCV+y8SM6tCY7NP
puNtmuKU6KC1eyaXhSvZgicIcpAfw/ZLzqjG4uE2MQtpQG4ZIMl6Nu+e0BYMUWo1
eES7gHAuSPn85vCJctm0ZWzCZGHzIlVZKqtKAW70tYO7QkRabRE/ka3jD+01unGh
WvXeg3xHiOZNj5zqtTYe1o/SkNCZJwfbSgVlHRvABk4Z6B9CC2UVtvb4OygEc0AJ
TiTf9XnsN37s8g==
-----END CERTIFICATE-----
"""

PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDevTIoya98QqZ2
mzxM6mTFcG7pwnMT0noGEG5XJdVcCEHJLJTE8AZj5tW0by6R/DyTnH+aobcSDHYJ
eqUr+YHrRPGjtT//p7mH93k8GnnScNcMH2NQ66So1sh05ycfciFjVPIuOcuqSCn6
onKUNi62SCQAtrMCKp9iV/ajLPdFoWmvbsVOdDcQzhGwZwwzfDb2Je7MibgNh4Fw
UevwecqbmBG/dYjnb3dAGT0Hlwr4lQluwPvUtu7kL/PFtrQD2TDoP0oDJL3vsx+7
EZdNuaW9dx1U62MqnfzDM922UejXotsdFpZ1y5FVOefb0nds44UBoLnv0k1wuqd+
7q36yCGZAgMBAAECggEBAKpTHP8psyKfSPHbpVHfz21Xm8jvY9Zdlef7OpUzniMB
QWUXzS+HqCtOwk520rLZomzyOHXDgd2wX7bB7XpiEqIZF3qrSCQ0WuCJMlDuogd1
OEzR171yZHijvaf/duBKAxQVShhlI8Oz6T36aQnDIRdMtRNCokJe24B1aWnAIdpA
teYmHptQvWMGaVs99UjoBgwUGqWPxU7tO0VIQLjWbWYLL+a053hX/qHgiM7LQPrL
AJkVj0ToOtEBE0wfYXlMSRPSz5i0yKxYEnS0czRA18ySbyGwxHstRYzR5GJ3C+gi
JoS0S+IkY1btZnGimAOe/VpXrRtdqb8mll+iJdEhsHECgYEA9F9g11FSDEkA6Muc
4gfZqxXeGz+OJRoYBuZrRNEC8RMwCbQ+xWzggakXw5YCLWbpXbg4fBlNzkWS0adE
fDuUekhTQiFxPJoMtErWkqGaWMMLzJoUgQ+TVwwLnFVbUPT4R/sb59qMC+NwMWh4
GDg3A4WEMNjrcU0+7QTXVut/C90CgYEA6VZOi4+Ql/xhtKrdmqJnwsi+/4eDxqcv
3Ag5sUmxgv3WQz0fXezqGyGNBz8+lpre4lMr+0sNWAHU+FPLE/cCmGn4Hq/10EBU
XJw7xlUwl4QDjEAjxEIm0MxIYAGJ9uXhDQgbXJS9JBMSc8mpbdHB9ekOE60Ul/B1
3ImguBWbXu0CgYEA4wAOZzUlMEBIVfd+HgEI04IWtd0N360jkJVOI7i8MNCQGROU
E7SVwBwg9RBNqXslYGeWIMEoo2nBfnsQhQ6bWBQDMzT5iT/YeUnjlIYFaFqWhVLD
pTeguIV565jmoIdOcx7xxygeW5TETUEr/eOKRv0p1G5MFw2YXHfYyOctNwkCgYEA
jgYcVNITfo79oYwGymJjqamqp7oCOV31wYW4J/Lk+wgp7E890lurusvXHTwfimfF
lhhtwszR2Gl1CZlnGEXW7JJDldogUpt1PdFSiMu9gdu2lR1NJ93j5l8RBm6pXQBa
1SXEEbvuzBBXwOZUHCX6WwV5rfxBdqHD+3JBwwpTwZkCgYAuIF+PrleDVimXmEEs
QmCmsRtTxtO8GgjoAr474+/XFZuf6AP3of4hviGSfnTrMAbD+AdJQSFTxishZ8gV
1xVPqKZapHFfA0ixYxu1oXCeRHATFn7Z8RNWAbk20JGxo/S2/qQfX2e9TLdpxAug
az9pYJBCvMx3SfOBIY70vIx2qA==
-----END PRIVATE KEY-----
"""
